#!name=去广告合集
#!desc=目前只有:中国移动,qq邮箱

[General]
force-http-engine-hosts = %APPEND% sdk.alibaba.com.ailbaba.me
tcp-connection = true

[URL Rewrite]

# qq邮箱开屏 rescdn.qqmail.com
^https:\/\/rescdn\.qqmail\.com\/qqmail\/images\/.+\.(png|jpg)$ - reject

[Map Local]
# 中国移动开屏 client.app.coc.10086.cn
^https?:\/\/client\.app\.coc\.10086\.cn\/biz-orange\/DN\/(explorePage\/getAdverList|init\/startInit) data="https://raw.githubusercontent.com/Keywos/rule/main/mocks//reject-200.txt"

# 微信公众号底部 mp.weixin.qq.com
^https?:\/\/mp\.weixin\.qq\.com\/mp\/getappmsgad data="https://raw.githubusercontent.com/Keywos/rule/main/mocks//WeChat.json"

[MITM]
h2 = true
hostname = %APPEND% client.app.coc.10086.cn, list-app-m.i4.cn, search-app-m.i4.cn, mp.weixin.qq.com, webappcfg.paas.cmbchina.com, rescdn.qqmail.com, us.l.qq.com, napi.ithome.com, api.zuihuimai.com, dat.ruanmei.com
